### ISSUE TITLE
line sensors wiring 

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/rpi-python-line-following#8]
Feedback from projects site.

"By splitting the wire to feed two sensors, you will still have 5 volts, only the current will get splitted. Is it ok to power the sensors with 5 v?"

"URL: /en/projects/rpi-python-line-following/5 Sounds like a neat trick: Two 3.3 v Sensor on a 5V pin. But then you should not align them parallel, but in series. The way you do it, both of the sensors will be on 5v."

**Comment by MarcScott** [comment]
Vin on these is 3.3V/5V so this is fine - https://www.aliexpress.com/item/Line-tracking-Sensor-For-robotic-and-car-DIY-Arduino-projects-Digital-Out/32654587628.html

Connecting them in series would give 2.5V which wouldn't be enough.
